/**
 * 詰めはさみの問題。
 *
 * 「攻め方が指し始めて、相手がどう受けても N 手で必ず勝つ」局面を並べる。
 *
 * 局面は core/diagram.ts の書き方で持つ。持ち駒は 0 にしてある。
 * 打つ手が混ざると読む手が一気に増えて、答え合わせも受け方の応手も重くなるため。
 *
 * ここに並べたものは puzzles.test.ts が「ちょうど N 手詰め」であることと
 * 「最初の一手が1通りしかない」ことを毎回確かめる。
 * 手で書き足したものが成り立っていなければ、テストが落ちて気づける。
 *
 * 題名は持たない。一覧では手数の中の並び順で「第N問」と呼ぶ。
 */

import { parseDiagram } from "./diagram";
import type { GameState, Player } from "./types";

export interface Puzzle {
  readonly id: string;
  /** 何手で詰むか。奇数。 */
  readonly plies: number;
  /** 盤の並び。"." 空き / "A" 黒 / "a" 黒の封じ / "B" 白 / "b" 白の封じ */
  readonly rows: readonly string[];
  /** 攻め方。最初の手番。 */
  readonly turn: Player;
  /** 残りの持ち駒。詰めはさみは 0。 */
  readonly hands: Readonly<Record<Player, number>>;
  /** 1手で動ける距離。 */
  readonly moveRange: number;
}

/** 問題の開始局面を作る。 */
export function puzzleState(puzzle: Puzzle): GameState {
  return parseDiagram(puzzle.rows, {
    turn: puzzle.turn,
    hands: puzzle.hands,
    moveRange: puzzle.moveRange,
    // 持ち駒は使わないので、手番表示に空の丸を並べない
    handSize: 0,
  });
}

const NO_HANDS = { A: 0, B: 0 } as const;

export const PUZZLES: readonly Puzzle[] = [
  /* ---------------- 1手 ---------------- */
  {
    id: "kabe-1",
    plies: 1,
    rows: ["B.A", "A..", "..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-01",
    plies: 1,
    rows: ["BA...", ".....", "AB..A", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-02",
    plies: 1,
    rows: ["..ABB", ".....", "...A.", ".....", "..A.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-03",
    plies: 1,
    rows: ["BAB..", ".A...", ".....", ".....", "...A."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-04",
    plies: 1,
    rows: [".....", "...A.", "..BBA", "....A", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-05",
    plies: 1,
    rows: [".....", ".....", ".A.B.", "A....", "B.A.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-06",
    plies: 1,
    rows: ["...BB", "A....", "....A", ".A...", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-07",
    plies: 1,
    rows: ["B....", "AA...", ".....", "....A", "....B"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-08",
    plies: 1,
    rows: [".AB..", "..AA.", "B....", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-09",
    plies: 1,
    rows: [".....", ".....", "....A", "AAB..", "B...."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-10",
    plies: 1,
    rows: [".....", ".....", ".....", "A..A.", "ABB.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-11",
    plies: 1,
    rows: ["BABA.", ".....", "..A..", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-12",
    plies: 1,
    rows: ["B.A..", "B....", ".....", "...A.", ".A..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-13",
    plies: 1,
    rows: [".....", ".....", "...A.", "..B..", "..ABA"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-14",
    plies: 1,
    rows: ["...A.", "....A", ".....", "...BB", "....A"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t1-15",
    plies: 1,
    rows: [".....", ".....", ".....", "..AA.", "BBA.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "futatsu-1",
    plies: 1,
    rows: [".B...", ".....", "AA...", "....A", "BB..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "hidarishita-1",
    plies: 1,
    rows: ["B..A.", "BA...", "....A", ".....", ".A.B."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "obankado-1",
    plies: 1,
    rows: ["BB.....", ".A.....", "...A...", ".......", "A......", ".......", "......."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "obanue-1",
    plies: 1,
    rows: [".....BB", "..A..A.", ".......", "...A...", ".......", ".......", "......."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  /* ---------------- 3手 ---------------- */
  {
    id: "chirabaru-3",
    plies: 3,
    rows: ["..B..", ".....", ".A..A", "A....", ".BB.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "hidariue-3",
    plies: 3,
    rows: ["BA.B.", "B.A..", ".A...", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "migihen-3",
    plies: 3,
    rows: ["...A.", "..A.B", ".....", "..A.B", "....B"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "migiue-3",
    plies: 3,
    rows: ["...BB", "..A.A", "B....", ".....", "..A.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "sumi-3",
    plies: 3,
    rows: ["...AB", "..AB.", "....A", ".....", "B...."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-01",
    plies: 3,
    rows: ["...A.", "....B", "...AB", ".....", "...BA"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-02",
    plies: 3,
    rows: ["A....", "BA...", ".B...", ".A...", "...B."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-03",
    plies: 3,
    rows: [".A...", "B.A..", "A....", "..B..", ".B..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-04",
    plies: 3,
    rows: [".....", ".....", "...AB", "B..A.", "..A.B"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-05",
    plies: 3,
    rows: ["...B.", "..AAA", ".....", "..B..", ".B..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-06",
    plies: 3,
    rows: ["B.A..", ".....", ".A...", "A....", ".BB.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-07",
    plies: 3,
    rows: [".....", ".....", "..AB.", "....A", "A..BB"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-08",
    plies: 3,
    rows: [".....", "A...A", ".....", ".B..B", "BA..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-09",
    plies: 3,
    rows: [".BA..", "A.A..", "...B.", ".....", "..B.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t3-10",
    plies: 3,
    rows: [".A.AB", ".....", "...A.", ".....", "...BB"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "yoko-3",
    plies: 3,
    rows: [".....", "..A..", "..ABB", "....B", "...A."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "hidari-3",
    plies: 3,
    rows: ["A.B..", ".A...", "..B.B", "..A.B", "...A."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "irikumu-3",
    plies: 3,
    rows: ["ABB..", ".B...", "..A.A", ".A...", "B...."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "hiroba-3",
    plies: 3,
    rows: [".......", "B....A.", ".......", "A......", ".......", ".B.....", "BA....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "shitahen-3",
    plies: 3,
    rows: [".......", ".......", "....A..", ".......", ".A.....", "A......", "BB.B..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  /* ---------------- 5手 ---------------- */
  {
    id: "chuoshita-5",
    plies: 5,
    rows: [".....", ".B...", "B..A.", "...A.", "..AB."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "hanareta-5",
    plies: 5,
    rows: ["A....", ".....", "...AA", "B...B", "..B.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "jouhen-5",
    plies: 5,
    rows: ["B.B..", ".....", "AA...", "...A.", ".B..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "kado-5",
    plies: 5,
    rows: ["BA...", "A.A..", "B....", ".....", "B...."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "migi-5",
    plies: 5,
    rows: ["....B", "....B", "....A", "..A.B", "..A.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "shita-5",
    plies: 5,
    rows: [".....", ".....", "B.A..", "..A..", ".A.BB"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-01",
    plies: 5,
    rows: ["..ABB", "...BA", "A....", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-02",
    plies: 5,
    rows: [".....", ".....", "..A.B", ".B..A", "...AB"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-03",
    plies: 5,
    rows: [".AAB.", "B....", "B.A..", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-04",
    plies: 5,
    rows: ["BA...", "BB...", ".....", ".A..A", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-05",
    plies: 5,
    rows: [".BA..", "A....", "A....", ".B...", "B...."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-06",
    plies: 5,
    rows: [".A.BB", ".A..A", ".....", "....B", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-07",
    plies: 5,
    rows: ["....B", ".....", "...AB", "...A.", "A...B"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-08",
    plies: 5,
    rows: ["..BA.", "B.A.B", "....A", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-09",
    plies: 5,
    rows: ["..A.B", "..AA.", ".....", "B....", "...B."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t5-10",
    plies: 5,
    rows: ["BA...", "BB...", "..A..", ".....", "...A."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "ue-5",
    plies: 5,
    rows: ["..B.B", "..AA.", ".B...", ".....", "A...."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "naname-5",
    plies: 5,
    rows: ["A....", "A.B..", "...A.", "B..A.", "..B.B"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "oban-5",
    plies: 5,
    rows: ["..A....", "B.A....", "B......", ".......", ".......", ".....A.", ".B....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "sankaku-5",
    plies: 5,
    rows: ["...B...", ".......", ".......", ".......", ".A.A...", ".A.....", "B.B...."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  /* ---------------- 7手 ---------------- */
  {
    id: "t7-13",
    plies: 7,
    rows: [".A.A.", "B....", "A...B", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-01",
    plies: 7,
    rows: [".....", "B....", ".A...", "B.A..", "..B.A"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-02",
    plies: 7,
    rows: [".....", "BAB..", ".....", "B....", ".AA.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-03",
    plies: 7,
    rows: ["....B", "..A.B", "..AA.", "...B.", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-04",
    plies: 7,
    rows: [".A..B", ".....", "A..AB", "....B", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-05",
    plies: 7,
    rows: ["...A.", "B.A..", "A..B.", "..B..", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-06",
    plies: 7,
    rows: [".BA..", ".....", ".A.A.", ".....", "...BB"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-07",
    plies: 7,
    rows: ["...BB", "..A..", "...A.", "....B", ".A..."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-08",
    plies: 7,
    rows: ["....A", "....B", "..A.A", ".....", "..BB."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-09",
    plies: 7,
    rows: [".....", "B...A", ".....", ".A...", "..BAB"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-10",
    plies: 7,
    rows: ["...BB", "..A..", ".A.A.", ".....", "..B.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-11",
    plies: 7,
    rows: ["BAB..", "...A.", ".A...", ".....", "..B.."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-12",
    plies: 7,
    rows: ["AB..B", "..BA.", "....A", ".....", "....."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-14",
    plies: 7,
    rows: [".....", "..B..", ".....", "A..A.", "BA..B"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-15",
    plies: 7,
    rows: [".....", "...AB", ".....", "..A.B", "B...A"],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-16",
    plies: 7,
    rows: [".B.B.", "....A", "...A.", ".....", "..AB."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-17",
    plies: 7,
    rows: [".....", "..B..", ".A...", "A.A..", "B..B."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-18",
    plies: 7,
    rows: [".....", ".....", ".B.AA", "....B", ".A.B."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-19",
    plies: 7,
    rows: [".....", "..B..", "...AA", ".A...", ".B.B."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
  {
    id: "t7-20",
    plies: 7,
    rows: [".....", "B....", ".....", "A.A.B", "..AB."],
    turn: "A",
    hands: NO_HANDS,
    moveRange: 1,
  },
];

export function puzzleById(id: string): Puzzle | null {
  return PUZZLES.find((puzzle) => puzzle.id === id) ?? null;
}
